language: elixir
elixir:
  - 1.3.1
otp_release:
  - 18.0
  - 18.1
  - 18.2
  - 18.3
  - 19.0
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - cp config/travis.exs config/test.travis.exs
