language: elixir
elixir:
  - 1.3.3
otp_release:
  - 18.1
  - 18.2
  - 18.3
  - 19.0
  - 19.1
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - cp config/travis.exs config/test.travis.exs
env:
  - MIX_ENV=test
script: mix coveralls.travis
